json is better than nothing
html errors are forcing node to throw an error, unsure of the cause but
at least this works.

Error:

```
_http_outgoing.js:331
    throw new Error('Can\'t set headers after they are sent.');
          ^
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader
(_http_outgoing.js:331:11)
    at ServerResponse.header
(/Users/nick/dev/indicator.email/node_modules/express/lib/response.js:66
6:10)
    at ServerResponse.res.contentType.res.type
(/Users/nick/dev/indicator.email/node_modules/express/lib/response.js:53
2:15)
    at ServerResponse.send
(/Users/nick/dev/indicator.email/node_modules/express/lib/response.js:12
1:14)
    at fn
(/Users/nick/dev/indicator.email/node_modules/express/lib/response.js:90
0:10)
    at Immediate._onImmediate
(/Users/nick/dev/indicator.email/node_modules/express-handlebars/lib/uti
ls.js:34:13)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
```